@ComputerRepairSystem.api_HostAddress = http://localhost:5285

GET {{ComputerRepairSystem.api_HostAddress}}/weatherforecast/
Accept: application/json

### DELETE ALL TEST DATA
DELETE {{ComputerRepairSystem.api_HostAddress}}/api/ServiceRequests/all

### 